on:
  push:
    branches:
      - 'fix/**'
      - 'master'
      - 'main'
  repository_dispatch:
    types: [release-to-env,clean-staging]
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    - uses: actions/checkout@v2
    - uses: debianmaster/set-gitref-env@fix/chat-ops
    - name: Get the output
      run: |
        echo ${{ toJson(github) }}
        echo ${RELEASE_TAG}
