on:
  push:
    branches:
      - 'fix/**'
      - 'master'
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    - uses: actions/checkout@v2
    - uses: debianmaster/set-gitref-env@fix/set-env-depricate
    - name: Get the output
      run: |
        echo ${RELEASE_TAG}